BlogTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: BlogTable-${self:provider.stage}
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      - AttributeName: slug
        AttributeType: S

    KeySchema:
      - AttributeName: id
        KeyType: HASH

    GlobalSecondaryIndexes:
      - IndexName: slug-index
        KeySchema:
          - AttributeName: slug
            KeyType: HASH
        Projection:
          ProjectionType: ALL

SuscriptorsTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: SuscriptorsTable-${self:provider.stage}
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: id
        AttributeType: S

    KeySchema:
      - AttributeName: id
        KeyType: HASH

PodcastTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: PodcastTable-${self:provider.stage}
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      - AttributeName: url
        AttributeType: S

    KeySchema:
      - AttributeName: id
        KeyType: HASH

    GlobalSecondaryIndexes:
      - IndexName: url-index
        KeySchema:
          - AttributeName: url
            KeyType: HASH
        Projection:
          ProjectionType: ALL
